version: '3'

services:
  openvpn:
    build: .
    container_name: openvpn-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn-data:/etc/openvpn
    restart: unless-stopped
    privileged: true  # Adicionando modo privilegiado para garantir acesso completo
    # Você pode descomentar e modificar a linha abaixo para definir o IP do servidor manualmente
    environment:
     - OVPN_SERVER_IP=192.168.29.131  # Substitua pelo IP real do seu servidor
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Ajuda a descobrir o IP do host

volumes:
  openvpn-data:
